"""ORCA proactive alert subsystem (PLAN.md Phase 8).

The part of ORCA that speaks without being asked. Everything else in the system answers a
question; this decides, on a schedule, that somebody needs to know something now.

That inverts the usual burden of proof. An answered question is checked by the person who
asked it; an unsolicited alert at 4 a.m. is not, so it has to be right, explainable, and
rare enough to still be believed the twentieth time. Four properties carry that:

1. **Every alert is one rule's arithmetic.** :mod:`orca_alerts.triggers` holds the rules;
   each records the observed value, the threshold and where the threshold came from. CAP
   severity, urgency and certainty are looked up from tables in :mod:`orca_alerts.cap`.
   **No language model decides whether to warn anybody, or how urgently.**
2. **Suppression protects the channel; escalation overrides suppression.** Alert fatigue is
   what makes a proactive system worse than none, so repeats are deduplicated — but a rise
   in severity, or a drift warning whose time has halved, always goes out.
3. **Sent is not delivered.** The delivery router tries every channel and records each
   outcome, so an alert that reached nobody is visible as such.
4. **ORCA's reach ends at cellular coverage, and it says so.**
   :mod:`orca_alerts.handoff` routes the offshore leg to GEMINI, DAT-SG and Sagarmitra.
   ORCA complements those services; it does not compete with them and must never be
   presented as an offshore channel.

Every evaluation, including the suppressed ones, is written to an audit record with a
Phase 6 provenance graph — because the question after an incident is usually *why was this
boat not warned*, and only the suppressed records can answer it.
"""

from orca_alerts.audit import (
    ALERT_FORMULA_ID,
    ALERT_FORMULA_VERSION,
    AlertAuditRecord,
    TickAudit,
    build_alert_provenance,
)
from orca_alerts.cap import (
    CAP_NAMESPACE,
    CATEGORY_BY_TRIGGER,
    CERTAINTY_BY_TRIGGER,
    DEFAULT_SENDER,
    RESPONSE_BY_TRIGGER,
    SEVERITY_BY_OUTCOME,
    SEVERITY_ORDER,
    URGENCY_BY_TRIGGER,
    CapAlert,
    CapArea,
    CapCategory,
    CapCertainty,
    CapInfo,
    CapMsgType,
    CapResponseType,
    CapScope,
    CapSeverity,
    CapStatus,
    CapUrgency,
    CapValidationIssue,
    certainty_for,
    make_identifier,
    severity_for,
    urgency_for,
    validate,
)
from orca_alerts.conditions import (
    WIND_RADIUS_KNOTS,
    CycloneSystem,
    GeoPolygon,
    HazardPicture,
    HazardSource,
    MarineConditions,
    WindRadius,
)
from orca_alerts.dedup import (
    DRIFT_RESEND_FRACTION,
    SUPPRESSION_WINDOW,
    AlertDeduplicator,
    AlertKey,
    AlertRecord,
    Decision,
    DecisionKind,
    SuppressionSummary,
    hazard_ref_for,
)
from orca_alerts.delivery import (
    MAX_PUSH_PAYLOAD_BYTES,
    SMS_MIN_SEVERITY,
    AlertPayload,
    ChannelUnavailableError,
    DeliveryAttempt,
    DeliveryChannel,
    DeliveryOutcome,
    DeliveryReport,
    DeliveryRouter,
    FcmChannel,
    InAppChannel,
    SmsChannel,
    WebPushChannel,
    WebSocketChannel,
    payload_from_alert,
)
from orca_alerts.handoff import (
    DAT_SG,
    GEMINI,
    HANDOFF_STATEMENT,
    MARGINAL_COVERAGE_KM,
    OFFSHORE_SERVICES,
    RELIABLE_COVERAGE_KM,
    SAGARMITRA,
    CoverageZone,
    HandoffNotice,
    OffshoreService,
    coverage_zone,
    handoff_for,
)
from orca_alerts.messages import (
    TEMPLATE_BY_TRIGGER,
    AlertContext,
    AlertMessage,
    MissingAlertContextError,
    build_message,
    build_slots,
    event_name,
)
from orca_alerts.scheduler import (
    DATASET_BY_TRIGGER,
    DEFAULT_ALERT_LIFETIME,
    AlertScheduler,
    TickConfig,
)
from orca_alerts.subscriber import (
    MAX_POSITION_AGE,
    ChannelEndpoint,
    DeliveryChannelKind,
    Fleet,
    SkippedSubscriber,
    SkipReason,
    Subscriber,
    VesselState,
    classify_skip,
)
from orca_alerts.triggers import (
    DRIFT_IMMEDIATE_HORIZON,
    DRIFT_WARNING_HORIZON,
    LIGHTNING_WARNING_STRIKES,
    LIGHTNING_WATCH_STRIKES,
    MAX_CONDITION_AGE,
    OUTCOME_RANK,
    SQUALL_WARNING_PROBABILITY,
    SQUALL_WATCH_PROBABILITY,
    TriggerId,
    TriggerOutcome,
    TriggerResult,
    check_cyclone_cone,
    check_cyclone_wind,
    check_geofence_proximity,
    check_lightning,
    check_predictive_drift,
    check_squall,
    check_wave_height,
    check_wind_speed,
    evaluate_cyclones,
    evaluate_vessel_conditions,
    worst,
)
from orca_alerts.workflows import (
    SAMPLE_SHELTERS,
    SHELTER_REGISTRY_IS_SAMPLE,
    AuthorityBroadcast,
    BoatRecall,
    CycloneShelter,
    HarbourAdvisory,
    HarbourStatus,
    RecallUrgency,
    ShelterGuidance,
    WorkflowDispatch,
    broadcast_to_cap,
    dispatch_recall,
    harbour_advisory_to_cap,
    nearest_shelter,
    recall_to_cap,
)

SERVICE_NAME = "orca-alerts"
__version__ = "0.1.0"

__all__ = [
    "ALERT_FORMULA_ID",
    "ALERT_FORMULA_VERSION",
    "CAP_NAMESPACE",
    "CATEGORY_BY_TRIGGER",
    "CERTAINTY_BY_TRIGGER",
    "DATASET_BY_TRIGGER",
    "DAT_SG",
    "DEFAULT_ALERT_LIFETIME",
    "DEFAULT_SENDER",
    "DRIFT_IMMEDIATE_HORIZON",
    "DRIFT_RESEND_FRACTION",
    "DRIFT_WARNING_HORIZON",
    "GEMINI",
    "HANDOFF_STATEMENT",
    "LIGHTNING_WARNING_STRIKES",
    "LIGHTNING_WATCH_STRIKES",
    "MARGINAL_COVERAGE_KM",
    "MAX_CONDITION_AGE",
    "MAX_POSITION_AGE",
    "MAX_PUSH_PAYLOAD_BYTES",
    "OFFSHORE_SERVICES",
    "OUTCOME_RANK",
    "RELIABLE_COVERAGE_KM",
    "RESPONSE_BY_TRIGGER",
    "SAGARMITRA",
    "SAMPLE_SHELTERS",
    "SERVICE_NAME",
    "SEVERITY_BY_OUTCOME",
    "SEVERITY_ORDER",
    "SHELTER_REGISTRY_IS_SAMPLE",
    "SMS_MIN_SEVERITY",
    "SQUALL_WARNING_PROBABILITY",
    "SQUALL_WATCH_PROBABILITY",
    "SUPPRESSION_WINDOW",
    "TEMPLATE_BY_TRIGGER",
    "URGENCY_BY_TRIGGER",
    "WIND_RADIUS_KNOTS",
    "AlertAuditRecord",
    "AlertContext",
    "AlertDeduplicator",
    "AlertKey",
    "AlertMessage",
    "AlertPayload",
    "AlertRecord",
    "AlertScheduler",
    "AuthorityBroadcast",
    "BoatRecall",
    "CapAlert",
    "CapArea",
    "CapCategory",
    "CapCertainty",
    "CapInfo",
    "CapMsgType",
    "CapResponseType",
    "CapScope",
    "CapSeverity",
    "CapStatus",
    "CapUrgency",
    "CapValidationIssue",
    "ChannelEndpoint",
    "ChannelUnavailableError",
    "CoverageZone",
    "CycloneShelter",
    "CycloneSystem",
    "Decision",
    "DecisionKind",
    "DeliveryAttempt",
    "DeliveryChannel",
    "DeliveryChannelKind",
    "DeliveryOutcome",
    "DeliveryReport",
    "DeliveryRouter",
    "FcmChannel",
    "Fleet",
    "GeoPolygon",
    "HandoffNotice",
    "HarbourAdvisory",
    "HarbourStatus",
    "HazardPicture",
    "HazardSource",
    "InAppChannel",
    "MarineConditions",
    "MissingAlertContextError",
    "OffshoreService",
    "RecallUrgency",
    "ShelterGuidance",
    "SkipReason",
    "SkippedSubscriber",
    "SmsChannel",
    "Subscriber",
    "SuppressionSummary",
    "TickAudit",
    "TickConfig",
    "TriggerId",
    "TriggerOutcome",
    "TriggerResult",
    "VesselState",
    "WebPushChannel",
    "WebSocketChannel",
    "WindRadius",
    "WorkflowDispatch",
    "__version__",
    "broadcast_to_cap",
    "build_alert_provenance",
    "build_message",
    "build_slots",
    "certainty_for",
    "check_cyclone_cone",
    "check_cyclone_wind",
    "check_geofence_proximity",
    "check_lightning",
    "check_predictive_drift",
    "check_squall",
    "check_wave_height",
    "check_wind_speed",
    "classify_skip",
    "coverage_zone",
    "dispatch_recall",
    "evaluate_cyclones",
    "evaluate_vessel_conditions",
    "event_name",
    "handoff_for",
    "harbour_advisory_to_cap",
    "hazard_ref_for",
    "make_identifier",
    "nearest_shelter",
    "payload_from_alert",
    "recall_to_cap",
    "severity_for",
    "urgency_for",
    "validate",
    "worst",
]
